language: c

before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash scripts/linux/install.sh; export OPENRCT_MAKE_OPTS="-j2 -k all openrct2-cli" ; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo gem install xcpretty-travis-formatter; fi

sudo: required
dist: trusty
env:
    global:
        - OPENRCT2_VERSION="0.0.8"

matrix:
    include:
        - os: linux
          language: android
          dist: precise
          before_install: []
          android:
            components:
              - build-tools-25.0.2
#               - tools # to get the new `repository-11.xml`
#               - tools # to install latest Android SDK tools (currently at 25.2.5)
#               - platform-tools
#               - build-tools-25.0.2
#               - android-25
#               - extra-android-m2repository
          jdk: oraclejdk8
          before_script:
            - pushd ~
            - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
            - unzip -qo sdk-tools-linux-3859397.zip
            - rm -Rf "$ANDROID_HOME/tools"
            - mv tools "$ANDROID_HOME/tools"
            - popd
            - 'echo "count=0" >  ~/.android/repositories.cfg'
            - '"$ANDROID_HOME/tools/bin/sdkmanager" --list'
            - 'echo y | "$ANDROID_HOME/tools/bin/sdkmanager" platform-tools'
            - 'echo y | "$ANDROID_HOME/tools/bin/sdkmanager" "platforms;android-25"'
            - 'echo y | "$ANDROID_HOME/tools/bin/sdkmanager" "cmake;3.6.3155560"'
            - '"$ANDROID_HOME/tools/bin/sdkmanager" ndk-bundle'
            - '"$ANDROID_HOME/tools/bin/sdkmanager" --list'
            - 'export ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"'
            - 'cd src/openrct2-android'
            - TERM=dumb # Makes Gradle use 'boring' output
          script:
            - './gradlew app:assemblePR'
          after_success:
            - curl --progress-bar --upload-file app/build/outputs/apk/app-arm-pr.apk https://transfer.sh/openrct2-android-arm.apk -o link && cat link
            - curl --progress-bar --upload-file app/build/outputs/apk/app-x86-pr.apk https://transfer.sh/openrct2-android-x86.apk -o link && cat link

script:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash scripts/linux/build.sh ; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then set -o pipefail && xcodebuild | xcpretty -f `xcpretty-travis-formatter`; fi

notifications:
    on_failure: change
    on_success: change

cache:
    directories:
        - .cache
    apt: true
